server:
  port: 8080

spring:
  application:
    name: TenantHub
  datasource:
    url: jdbc:postgresql://46.225.97.71:5432/postgres?currentSchema=tenant_hub
    username: postgres
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: false
  mvc:
    problemdetails:
      enabled: true
jwt:
  secret: 5rDmTtqp7KKanOl22OzBh6lC509zs1uuoLoiJkf97gAveb3m1s8SvRn1ugaxvbSm+lwCEn3FG7oRp9JXv58/Dg==
  access-token-expiration: 3600000    # 1 saat (ms)
  refresh-token-expiration: 604800000 # 7 gün (ms)
logging:
  level:
    root: INFO
    com.obntech.tenanthub: DEBUG
    org.hibernate.SQL: DEBUG
