-- ---------------------------------------------------------------
-- REAL_ESTATE
-- ---------------------------------------------------------------
CREATE SEQUENCE tenant_hub.SEQ_REAL_ESTATE START WITH 1 INCREMENT BY 1;

CREATE TABLE tenant_hub.REAL_ESTATE (
    ID              BIGINT          NOT NULL DEFAULT nextval('tenant_hub.SEQ_REAL_ESTATE'),
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     VARCHAR(1000),
    TYPE            VARCHAR(50)     NOT NULL,
    PROVINCE        VARCHAR(100)    NOT NULL,
    DISTRICT        VARCHAR(100)    NOT NULL,
    NEIGHBORHOOD    VARCHAR(100)    NOT NULL,
    ADDRESS         VARCHAR(500)    NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_REAL_ESTATE        PRIMARY KEY (ID),
    CONSTRAINT CK_REAL_ESTATE_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IDX_REAL_ESTATE_NAME         ON tenant_hub.REAL_ESTATE (NAME);
CREATE INDEX IDX_REAL_ESTATE_TYPE         ON tenant_hub.REAL_ESTATE (TYPE);
CREATE INDEX IDX_REAL_ESTATE_PROVINCE     ON tenant_hub.REAL_ESTATE (PROVINCE);
CREATE INDEX IDX_REAL_ESTATE_DISTRICT     ON tenant_hub.REAL_ESTATE (DISTRICT);
CREATE INDEX IDX_REAL_ESTATE_NEIGHBORHOOD ON tenant_hub.REAL_ESTATE (NEIGHBORHOOD);

-- ---------------------------------------------------------------
-- REAL_ESTATE_HIS
-- ---------------------------------------------------------------
CREATE SEQUENCE tenant_hub.SEQ_REAL_ESTATE_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE tenant_hub.REAL_ESTATE_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('tenant_hub.SEQ_REAL_ESTATE_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     VARCHAR(1000),
    TYPE            VARCHAR(50)     NOT NULL,
    PROVINCE        VARCHAR(100)    NOT NULL,
    DISTRICT        VARCHAR(100)    NOT NULL,
    NEIGHBORHOOD    VARCHAR(100)    NOT NULL,
    ADDRESS         VARCHAR(500)    NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_REAL_ESTATE_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_REAL_ESTATE_HIS_ORIGINAL_ID ON tenant_hub.REAL_ESTATE_HIS (ORIGINAL_ID);

-- ---------------------------------------------------------------
-- REAL_ESTATE HISTORY TRIGGER
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION tenant_hub.FN_REAL_ESTATE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO tenant_hub.REAL_ESTATE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, TYPE, PROVINCE, DISTRICT, NEIGHBORHOOD, ADDRESS, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('tenant_hub.SEQ_REAL_ESTATE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.TYPE, NEW.PROVINCE, NEW.DISTRICT, NEW.NEIGHBORHOOD, NEW.ADDRESS, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO tenant_hub.REAL_ESTATE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, TYPE, PROVINCE, DISTRICT, NEIGHBORHOOD, ADDRESS, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('tenant_hub.SEQ_REAL_ESTATE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.TYPE, NEW.PROVINCE, NEW.DISTRICT, NEW.NEIGHBORHOOD, NEW.ADDRESS, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO tenant_hub.REAL_ESTATE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, TYPE, PROVINCE, DISTRICT, NEIGHBORHOOD, ADDRESS, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('tenant_hub.SEQ_REAL_ESTATE_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.TYPE, OLD.PROVINCE, OLD.DISTRICT, OLD.NEIGHBORHOOD, OLD.ADDRESS, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_REAL_ESTATE_HIS
    AFTER INSERT OR UPDATE OR DELETE ON tenant_hub.REAL_ESTATE
    FOR EACH ROW EXECUTE FUNCTION tenant_hub.FN_REAL_ESTATE_HIS();

-- ---------------------------------------------------------------
-- REAL_ESTATE PERMISSIONS
-- ---------------------------------------------------------------
INSERT INTO tenant_hub.PERMISSION (ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS, CREATED_BY, CREATED_DATE, CREATED_IP)
VALUES
    (nextval('tenant_hub.SEQ_PERMISSION'), 'REAL_ESTATE_CREATE', 'Gayrimenkul oluşturma yetkisi', 'REAL_ESTATE', 'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('tenant_hub.SEQ_PERMISSION'), 'REAL_ESTATE_READ',   'Gayrimenkul görüntüleme yetkisi', 'REAL_ESTATE', 'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('tenant_hub.SEQ_PERMISSION'), 'REAL_ESTATE_UPDATE', 'Gayrimenkul güncelleme yetkisi', 'REAL_ESTATE', 'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('tenant_hub.SEQ_PERMISSION'), 'REAL_ESTATE_DELETE', 'Gayrimenkul silme yetkisi',      'REAL_ESTATE', 'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1');
