-- ---------------------------------------------------------------
-- REAL_ESTATE: TENANT & LANDLORD kolonları ekleniyor
-- ---------------------------------------------------------------
ALTER TABLE tenant_hub.REAL_ESTATE
    ADD COLUMN TENANT_ID   BIGINT,
    ADD COLUMN LANDLORD_ID BIGINT;

ALTER TABLE tenant_hub.REAL_ESTATE
    ADD CONSTRAINT FK_REAL_ESTATE_TENANT   FOREIGN KEY (TENANT_ID)   REFERENCES tenant_hub.USERS(ID),
    ADD CONSTRAINT FK_REAL_ESTATE_LANDLORD FOREIGN KEY (LANDLORD_ID) REFERENCES tenant_hub.USERS(ID);

CREATE INDEX IDX_REAL_ESTATE_TENANT_ID   ON tenant_hub.REAL_ESTATE (TENANT_ID);
CREATE INDEX IDX_REAL_ESTATE_LANDLORD_ID ON tenant_hub.REAL_ESTATE (LANDLORD_ID);

-- ---------------------------------------------------------------
-- REAL_ESTATE_HIS: TENANT & LANDLORD kolonları ekleniyor
-- ---------------------------------------------------------------
ALTER TABLE tenant_hub.REAL_ESTATE_HIS
    ADD COLUMN TENANT_ID   BIGINT,
    ADD COLUMN LANDLORD_ID BIGINT;

-- ---------------------------------------------------------------
-- TRIGGER fonksiyonunu güncelle
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION tenant_hub.FN_REAL_ESTATE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO tenant_hub.REAL_ESTATE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, TYPE, PROVINCE, DISTRICT, NEIGHBORHOOD, ADDRESS, STATUS,
            TENANT_ID, LANDLORD_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('tenant_hub.SEQ_REAL_ESTATE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.TYPE, NEW.PROVINCE, NEW.DISTRICT, NEW.NEIGHBORHOOD, NEW.ADDRESS, NEW.STATUS,
            NEW.TENANT_ID, NEW.LANDLORD_ID,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO tenant_hub.REAL_ESTATE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, TYPE, PROVINCE, DISTRICT, NEIGHBORHOOD, ADDRESS, STATUS,
            TENANT_ID, LANDLORD_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('tenant_hub.SEQ_REAL_ESTATE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.TYPE, NEW.PROVINCE, NEW.DISTRICT, NEW.NEIGHBORHOOD, NEW.ADDRESS, NEW.STATUS,
            NEW.TENANT_ID, NEW.LANDLORD_ID,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO tenant_hub.REAL_ESTATE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, TYPE, PROVINCE, DISTRICT, NEIGHBORHOOD, ADDRESS, STATUS,
            TENANT_ID, LANDLORD_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('tenant_hub.SEQ_REAL_ESTATE_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.TYPE, OLD.PROVINCE, OLD.DISTRICT, OLD.NEIGHBORHOOD, OLD.ADDRESS, OLD.STATUS,
            OLD.TENANT_ID, OLD.LANDLORD_ID,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;
