-- ---------------------------------------------------------------
-- RENT - ZAM_ORANI alanı ekleme
-- ---------------------------------------------------------------
ALTER TABLE devuser.RENT
    ADD COLUMN ZAM_ORANI NUMERIC(5,2) NULL;

-- ---------------------------------------------------------------
-- RENT_HIS - ZAM_ORANI alanı ekleme
-- ---------------------------------------------------------------
ALTER TABLE devuser.RENT_HIS
    ADD COLUMN ZAM_ORANI NUMERIC(5,2) NULL;

-- ---------------------------------------------------------------
-- RENT HISTORY TRIGGER - ZAM_ORANI dahil edildi
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION devuser.FN_RENT_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO devuser.RENT_HIS (
            ID, ORIGINAL_ID, REAL_ESTATE_ID, RENT_DATE, RENT_AMOUNT, CURRENCY, ZAM_ORANI, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('devuser.SEQ_RENT_HIS'), NEW.ID, NEW.REAL_ESTATE_ID, NEW.RENT_DATE, NEW.RENT_AMOUNT, NEW.CURRENCY, NEW.ZAM_ORANI, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO devuser.RENT_HIS (
            ID, ORIGINAL_ID, REAL_ESTATE_ID, RENT_DATE, RENT_AMOUNT, CURRENCY, ZAM_ORANI, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('devuser.SEQ_RENT_HIS'), NEW.ID, NEW.REAL_ESTATE_ID, NEW.RENT_DATE, NEW.RENT_AMOUNT, NEW.CURRENCY, NEW.ZAM_ORANI, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO devuser.RENT_HIS (
            ID, ORIGINAL_ID, REAL_ESTATE_ID, RENT_DATE, RENT_AMOUNT, CURRENCY, ZAM_ORANI, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('devuser.SEQ_RENT_HIS'), OLD.ID, OLD.REAL_ESTATE_ID, OLD.RENT_DATE, OLD.RENT_AMOUNT, OLD.CURRENCY, OLD.ZAM_ORANI, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;
